### ISSUE TITLE
수정 사항1

### ISSUE THREAD

**Issue by ghost** [Powering111/Ultimate-Tic-Tac-Toe#1]
게임 종료 후 칸 색깔 문제 해결 바람
시작 시의 마이너한 오류 해결 바람
음수 숫자 입력 문제 해결 바람
기여자와 베타테스터 추가 바람
![image](https://user-images.githubusercontent.com/83402028/125180764-ef8d6880-e238-11eb-92a4-1711a41320c7.png)

유저 친화적 UI 도입 바람
디자인 팀 도입이 시급해 보임

**Comment by ghost** [comment]
https://ultimate-t3.herokuapp.com/
https://bejofo.net/ttt
디자인에 참고 바람

**Comment by ghost** [comment]
https://www.cbc.ca/kids/games/all/ultimate-tic-tac-toe

**Comment by Powering111** [comment]
한 내용당 하나의 이슈를 사용해 주신다면 해결 여부나 분류 등이 더 수월해질 것 같습니다
다음에는 그렇게 해 주세요

**Comment by Powering111** [comment]
디자인을 제외하고 모두 수정 완료했습니다.
