### ISSUE TITLE
제안 사항

### ISSUE THREAD

**Issue by kms223344** [Powering111/Ultimate-Tic-Tac-Toe#5]
1~9 키패드를 이용해서 틱택토를 누를 수 있었으면 좋겠어요
모두 누를 수 있는 상황에서는 한번 눌러 커다란 틱택토 선택 -> 다시 눌러 작은 틱택토 선택

**Comment by Powering111** [comment]
모두 누를 수 있는 상황에서는 제외하고 제작하였습니다.
키 배치는 NumPad기준입니다.
